#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsRushX
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="adsrush")]
	public partial class AdvertisersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_AdsRushX_Advertiser(Table_AdsRushX_Advertiser instance);
    partial void UpdateTable_AdsRushX_Advertiser(Table_AdsRushX_Advertiser instance);
    partial void DeleteTable_AdsRushX_Advertiser(Table_AdsRushX_Advertiser instance);
    partial void InsertTable_AdsRushX_Advertisers_Stat(Table_AdsRushX_Advertisers_Stat instance);
    partial void UpdateTable_AdsRushX_Advertisers_Stat(Table_AdsRushX_Advertisers_Stat instance);
    partial void DeleteTable_AdsRushX_Advertisers_Stat(Table_AdsRushX_Advertisers_Stat instance);
    partial void InsertTable_AdsRushX_Advertisers_Banner(Table_AdsRushX_Advertisers_Banner instance);
    partial void UpdateTable_AdsRushX_Advertisers_Banner(Table_AdsRushX_Advertisers_Banner instance);
    partial void DeleteTable_AdsRushX_Advertisers_Banner(Table_AdsRushX_Advertisers_Banner instance);
    partial void InsertTable_AdsRushX_Advertisers_Campaign(Table_AdsRushX_Advertisers_Campaign instance);
    partial void UpdateTable_AdsRushX_Advertisers_Campaign(Table_AdsRushX_Advertisers_Campaign instance);
    partial void DeleteTable_AdsRushX_Advertisers_Campaign(Table_AdsRushX_Advertisers_Campaign instance);
    #endregion
		
		public AdvertisersDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["adsrushConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AdvertisersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdvertisersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdvertisersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdvertisersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_AdsRushX_Advertiser> Table_AdsRushX_Advertisers
		{
			get
			{
				return this.GetTable<Table_AdsRushX_Advertiser>();
			}
		}
		
		public System.Data.Linq.Table<Table_AdsRushX_Advertisers_Stat> Table_AdsRushX_Advertisers_Stats
		{
			get
			{
				return this.GetTable<Table_AdsRushX_Advertisers_Stat>();
			}
		}
		
		public System.Data.Linq.Table<Table_AdsRushX_Advertisers_Banner> Table_AdsRushX_Advertisers_Banners
		{
			get
			{
				return this.GetTable<Table_AdsRushX_Advertisers_Banner>();
			}
		}
		
		public System.Data.Linq.Table<Table_AdsRushX_Advertisers_Campaign> Table_AdsRushX_Advertisers_Campaigns
		{
			get
			{
				return this.GetTable<Table_AdsRushX_Advertisers_Campaign>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_AdsRushX_Advertisers")]
	public partial class Table_AdsRushX_Advertiser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _aid;
		
		private System.Nullable<int> _referaid;
		
		private string _referusername;
		
		private string _email;
		
		private string _username;
		
		private string _password;
		
		private string _fullname;
		
		private string _country;
		
		private string _paymentmethod;
		
		private string _skype;
		
		private string _whatsapp;
		
		private System.Nullable<int> _active;
		
		private System.Nullable<int> _suspended;
		
		private System.Nullable<System.DateTime> _signupdate;
		
		private string _signupip;
		
		private string _facebook;
		
		private string _linkedin;
		
		private string _websiteurl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnaidChanging(System.Nullable<int> value);
    partial void OnaidChanged();
    partial void OnreferaidChanging(System.Nullable<int> value);
    partial void OnreferaidChanged();
    partial void OnreferusernameChanging(string value);
    partial void OnreferusernameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnpaymentmethodChanging(string value);
    partial void OnpaymentmethodChanged();
    partial void OnskypeChanging(string value);
    partial void OnskypeChanged();
    partial void OnwhatsappChanging(string value);
    partial void OnwhatsappChanged();
    partial void OnactiveChanging(System.Nullable<int> value);
    partial void OnactiveChanged();
    partial void OnsuspendedChanging(System.Nullable<int> value);
    partial void OnsuspendedChanged();
    partial void OnsignupdateChanging(System.Nullable<System.DateTime> value);
    partial void OnsignupdateChanged();
    partial void OnsignupipChanging(string value);
    partial void OnsignupipChanged();
    partial void OnfacebookChanging(string value);
    partial void OnfacebookChanged();
    partial void OnlinkedinChanging(string value);
    partial void OnlinkedinChanged();
    partial void OnwebsiteurlChanging(string value);
    partial void OnwebsiteurlChanged();
    #endregion
		
		public Table_AdsRushX_Advertiser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aid", DbType="Int")]
		public System.Nullable<int> aid
		{
			get
			{
				return this._aid;
			}
			set
			{
				if ((this._aid != value))
				{
					this.OnaidChanging(value);
					this.SendPropertyChanging();
					this._aid = value;
					this.SendPropertyChanged("aid");
					this.OnaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referaid", DbType="Int")]
		public System.Nullable<int> referaid
		{
			get
			{
				return this._referaid;
			}
			set
			{
				if ((this._referaid != value))
				{
					this.OnreferaidChanging(value);
					this.SendPropertyChanging();
					this._referaid = value;
					this.SendPropertyChanged("referaid");
					this.OnreferaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referusername", DbType="NVarChar(3500)")]
		public string referusername
		{
			get
			{
				return this._referusername;
			}
			set
			{
				if ((this._referusername != value))
				{
					this.OnreferusernameChanging(value);
					this.SendPropertyChanging();
					this._referusername = value;
					this.SendPropertyChanged("referusername");
					this.OnreferusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(3500)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(3500)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(3500)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(3500)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(3500)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymentmethod", DbType="NVarChar(3500)")]
		public string paymentmethod
		{
			get
			{
				return this._paymentmethod;
			}
			set
			{
				if ((this._paymentmethod != value))
				{
					this.OnpaymentmethodChanging(value);
					this.SendPropertyChanging();
					this._paymentmethod = value;
					this.SendPropertyChanged("paymentmethod");
					this.OnpaymentmethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skype", DbType="NVarChar(3500)")]
		public string skype
		{
			get
			{
				return this._skype;
			}
			set
			{
				if ((this._skype != value))
				{
					this.OnskypeChanging(value);
					this.SendPropertyChanging();
					this._skype = value;
					this.SendPropertyChanged("skype");
					this.OnskypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whatsapp", DbType="NVarChar(3500)")]
		public string whatsapp
		{
			get
			{
				return this._whatsapp;
			}
			set
			{
				if ((this._whatsapp != value))
				{
					this.OnwhatsappChanging(value);
					this.SendPropertyChanging();
					this._whatsapp = value;
					this.SendPropertyChanged("whatsapp");
					this.OnwhatsappChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Int")]
		public System.Nullable<int> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suspended", DbType="Int")]
		public System.Nullable<int> suspended
		{
			get
			{
				return this._suspended;
			}
			set
			{
				if ((this._suspended != value))
				{
					this.OnsuspendedChanging(value);
					this.SendPropertyChanging();
					this._suspended = value;
					this.SendPropertyChanged("suspended");
					this.OnsuspendedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signupdate", DbType="Date")]
		public System.Nullable<System.DateTime> signupdate
		{
			get
			{
				return this._signupdate;
			}
			set
			{
				if ((this._signupdate != value))
				{
					this.OnsignupdateChanging(value);
					this.SendPropertyChanging();
					this._signupdate = value;
					this.SendPropertyChanged("signupdate");
					this.OnsignupdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signupip", DbType="NVarChar(3500)")]
		public string signupip
		{
			get
			{
				return this._signupip;
			}
			set
			{
				if ((this._signupip != value))
				{
					this.OnsignupipChanging(value);
					this.SendPropertyChanging();
					this._signupip = value;
					this.SendPropertyChanged("signupip");
					this.OnsignupipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facebook", DbType="NVarChar(3500)")]
		public string facebook
		{
			get
			{
				return this._facebook;
			}
			set
			{
				if ((this._facebook != value))
				{
					this.OnfacebookChanging(value);
					this.SendPropertyChanging();
					this._facebook = value;
					this.SendPropertyChanged("facebook");
					this.OnfacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linkedin", DbType="NVarChar(3500)")]
		public string linkedin
		{
			get
			{
				return this._linkedin;
			}
			set
			{
				if ((this._linkedin != value))
				{
					this.OnlinkedinChanging(value);
					this.SendPropertyChanging();
					this._linkedin = value;
					this.SendPropertyChanged("linkedin");
					this.OnlinkedinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_websiteurl", DbType="NVarChar(3500)")]
		public string websiteurl
		{
			get
			{
				return this._websiteurl;
			}
			set
			{
				if ((this._websiteurl != value))
				{
					this.OnwebsiteurlChanging(value);
					this.SendPropertyChanging();
					this._websiteurl = value;
					this.SendPropertyChanged("websiteurl");
					this.OnwebsiteurlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_AdsRushX_Advertisers_Stats")]
	public partial class Table_AdsRushX_Advertisers_Stat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _username;
		
		private System.Nullable<int> _month;
		
		private System.Nullable<int> _year;
		
		private System.Nullable<int> _imp;
		
		private System.Nullable<int> _clicks;
		
		private System.Nullable<float> _bid;
		
		private System.Nullable<float> _spending;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnmonthChanging(System.Nullable<int> value);
    partial void OnmonthChanged();
    partial void OnyearChanging(System.Nullable<int> value);
    partial void OnyearChanged();
    partial void OnimpChanging(System.Nullable<int> value);
    partial void OnimpChanged();
    partial void OnclicksChanging(System.Nullable<int> value);
    partial void OnclicksChanged();
    partial void OnbidChanging(System.Nullable<float> value);
    partial void OnbidChanged();
    partial void OnspendingChanging(System.Nullable<float> value);
    partial void OnspendingChanged();
    #endregion
		
		public Table_AdsRushX_Advertisers_Stat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(500)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_month", DbType="Int")]
		public System.Nullable<int> month
		{
			get
			{
				return this._month;
			}
			set
			{
				if ((this._month != value))
				{
					this.OnmonthChanging(value);
					this.SendPropertyChanging();
					this._month = value;
					this.SendPropertyChanged("month");
					this.OnmonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="Int")]
		public System.Nullable<int> year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this.OnyearChanging(value);
					this.SendPropertyChanging();
					this._year = value;
					this.SendPropertyChanged("year");
					this.OnyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imp", DbType="Int")]
		public System.Nullable<int> imp
		{
			get
			{
				return this._imp;
			}
			set
			{
				if ((this._imp != value))
				{
					this.OnimpChanging(value);
					this.SendPropertyChanging();
					this._imp = value;
					this.SendPropertyChanged("imp");
					this.OnimpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clicks", DbType="Int")]
		public System.Nullable<int> clicks
		{
			get
			{
				return this._clicks;
			}
			set
			{
				if ((this._clicks != value))
				{
					this.OnclicksChanging(value);
					this.SendPropertyChanging();
					this._clicks = value;
					this.SendPropertyChanged("clicks");
					this.OnclicksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bid", DbType="Real")]
		public System.Nullable<float> bid
		{
			get
			{
				return this._bid;
			}
			set
			{
				if ((this._bid != value))
				{
					this.OnbidChanging(value);
					this.SendPropertyChanging();
					this._bid = value;
					this.SendPropertyChanged("bid");
					this.OnbidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spending", DbType="Real")]
		public System.Nullable<float> spending
		{
			get
			{
				return this._spending;
			}
			set
			{
				if ((this._spending != value))
				{
					this.OnspendingChanging(value);
					this.SendPropertyChanging();
					this._spending = value;
					this.SendPropertyChanged("spending");
					this.OnspendingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_AdsRushX_Advertisers_Banners")]
	public partial class Table_AdsRushX_Advertisers_Banner : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _fullname;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _startdate;
		
		private System.Nullable<System.DateTime> _modifydate;
		
		private System.Nullable<int> _active;
		
		private string _comments;
		
		private string _leaderboard1;
		
		private string _leaderboard2;
		
		private string _leaderboard3;
		
		private string _superleaderboard;
		
		private string _billboard;
		
		private string _vertical;
		
		private string _rectangle;
		
		private string _custom;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnstartdateChanging(System.Nullable<System.DateTime> value);
    partial void OnstartdateChanged();
    partial void OnmodifydateChanging(System.Nullable<System.DateTime> value);
    partial void OnmodifydateChanged();
    partial void OnactiveChanging(System.Nullable<int> value);
    partial void OnactiveChanged();
    partial void OncommentsChanging(string value);
    partial void OncommentsChanged();
    partial void Onleaderboard1Changing(string value);
    partial void Onleaderboard1Changed();
    partial void Onleaderboard2Changing(string value);
    partial void Onleaderboard2Changed();
    partial void Onleaderboard3Changing(string value);
    partial void Onleaderboard3Changed();
    partial void OnsuperleaderboardChanging(string value);
    partial void OnsuperleaderboardChanged();
    partial void OnbillboardChanging(string value);
    partial void OnbillboardChanged();
    partial void OnverticalChanging(string value);
    partial void OnverticalChanged();
    partial void OnrectangleChanging(string value);
    partial void OnrectangleChanged();
    partial void OncustomChanging(string value);
    partial void OncustomChanged();
    #endregion
		
		public Table_AdsRushX_Advertisers_Banner()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(2500)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(2500)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(2500)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startdate", DbType="Date")]
		public System.Nullable<System.DateTime> startdate
		{
			get
			{
				return this._startdate;
			}
			set
			{
				if ((this._startdate != value))
				{
					this.OnstartdateChanging(value);
					this.SendPropertyChanging();
					this._startdate = value;
					this.SendPropertyChanged("startdate");
					this.OnstartdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifydate", DbType="Date")]
		public System.Nullable<System.DateTime> modifydate
		{
			get
			{
				return this._modifydate;
			}
			set
			{
				if ((this._modifydate != value))
				{
					this.OnmodifydateChanging(value);
					this.SendPropertyChanging();
					this._modifydate = value;
					this.SendPropertyChanged("modifydate");
					this.OnmodifydateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Int")]
		public System.Nullable<int> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="NVarChar(2500)")]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this.OncommentsChanging(value);
					this.SendPropertyChanging();
					this._comments = value;
					this.SendPropertyChanged("comments");
					this.OncommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leaderboard1", DbType="NVarChar(3500)")]
		public string leaderboard1
		{
			get
			{
				return this._leaderboard1;
			}
			set
			{
				if ((this._leaderboard1 != value))
				{
					this.Onleaderboard1Changing(value);
					this.SendPropertyChanging();
					this._leaderboard1 = value;
					this.SendPropertyChanged("leaderboard1");
					this.Onleaderboard1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leaderboard2", DbType="NVarChar(3500)")]
		public string leaderboard2
		{
			get
			{
				return this._leaderboard2;
			}
			set
			{
				if ((this._leaderboard2 != value))
				{
					this.Onleaderboard2Changing(value);
					this.SendPropertyChanging();
					this._leaderboard2 = value;
					this.SendPropertyChanged("leaderboard2");
					this.Onleaderboard2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leaderboard3", DbType="NVarChar(3500)")]
		public string leaderboard3
		{
			get
			{
				return this._leaderboard3;
			}
			set
			{
				if ((this._leaderboard3 != value))
				{
					this.Onleaderboard3Changing(value);
					this.SendPropertyChanging();
					this._leaderboard3 = value;
					this.SendPropertyChanged("leaderboard3");
					this.Onleaderboard3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_superleaderboard", DbType="NVarChar(3500)")]
		public string superleaderboard
		{
			get
			{
				return this._superleaderboard;
			}
			set
			{
				if ((this._superleaderboard != value))
				{
					this.OnsuperleaderboardChanging(value);
					this.SendPropertyChanging();
					this._superleaderboard = value;
					this.SendPropertyChanged("superleaderboard");
					this.OnsuperleaderboardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billboard", DbType="NVarChar(3500)")]
		public string billboard
		{
			get
			{
				return this._billboard;
			}
			set
			{
				if ((this._billboard != value))
				{
					this.OnbillboardChanging(value);
					this.SendPropertyChanging();
					this._billboard = value;
					this.SendPropertyChanged("billboard");
					this.OnbillboardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vertical", DbType="NVarChar(3500)")]
		public string vertical
		{
			get
			{
				return this._vertical;
			}
			set
			{
				if ((this._vertical != value))
				{
					this.OnverticalChanging(value);
					this.SendPropertyChanging();
					this._vertical = value;
					this.SendPropertyChanged("vertical");
					this.OnverticalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rectangle", DbType="NVarChar(3500)")]
		public string rectangle
		{
			get
			{
				return this._rectangle;
			}
			set
			{
				if ((this._rectangle != value))
				{
					this.OnrectangleChanging(value);
					this.SendPropertyChanging();
					this._rectangle = value;
					this.SendPropertyChanged("rectangle");
					this.OnrectangleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custom", DbType="NVarChar(3500)")]
		public string custom
		{
			get
			{
				return this._custom;
			}
			set
			{
				if ((this._custom != value))
				{
					this.OncustomChanging(value);
					this.SendPropertyChanging();
					this._custom = value;
					this.SendPropertyChanged("custom");
					this.OncustomChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_AdsRushX_Advertisers_Campaign")]
	public partial class Table_AdsRushX_Advertisers_Campaign : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _fullname;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _startdate;
		
		private string _campaignname;
		
		private string _campaignkeywords;
		
		private string _distype;
		
		private string _senurl;
		
		private System.Nullable<int> _active;
		
		private string _coupon;
		
		private string _comments;
		
		private System.Nullable<System.DateTime> _modifydate;
		
		private string _cat1;
		
		private string _cat2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnstartdateChanging(System.Nullable<System.DateTime> value);
    partial void OnstartdateChanged();
    partial void OncampaignnameChanging(string value);
    partial void OncampaignnameChanged();
    partial void OncampaignkeywordsChanging(string value);
    partial void OncampaignkeywordsChanged();
    partial void OndistypeChanging(string value);
    partial void OndistypeChanged();
    partial void OnsenurlChanging(string value);
    partial void OnsenurlChanged();
    partial void OnactiveChanging(System.Nullable<int> value);
    partial void OnactiveChanged();
    partial void OncouponChanging(string value);
    partial void OncouponChanged();
    partial void OncommentsChanging(string value);
    partial void OncommentsChanged();
    partial void OnmodifydateChanging(System.Nullable<System.DateTime> value);
    partial void OnmodifydateChanged();
    partial void Oncat1Changing(string value);
    partial void Oncat1Changed();
    partial void Oncat2Changing(string value);
    partial void Oncat2Changed();
    #endregion
		
		public Table_AdsRushX_Advertisers_Campaign()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(2500)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(2500)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(2500)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startdate", DbType="Date")]
		public System.Nullable<System.DateTime> startdate
		{
			get
			{
				return this._startdate;
			}
			set
			{
				if ((this._startdate != value))
				{
					this.OnstartdateChanging(value);
					this.SendPropertyChanging();
					this._startdate = value;
					this.SendPropertyChanged("startdate");
					this.OnstartdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaignname", DbType="NVarChar(2500)")]
		public string campaignname
		{
			get
			{
				return this._campaignname;
			}
			set
			{
				if ((this._campaignname != value))
				{
					this.OncampaignnameChanging(value);
					this.SendPropertyChanging();
					this._campaignname = value;
					this.SendPropertyChanged("campaignname");
					this.OncampaignnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaignkeywords", DbType="NVarChar(2500)")]
		public string campaignkeywords
		{
			get
			{
				return this._campaignkeywords;
			}
			set
			{
				if ((this._campaignkeywords != value))
				{
					this.OncampaignkeywordsChanging(value);
					this.SendPropertyChanging();
					this._campaignkeywords = value;
					this.SendPropertyChanged("campaignkeywords");
					this.OncampaignkeywordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distype", DbType="NVarChar(2500)")]
		public string distype
		{
			get
			{
				return this._distype;
			}
			set
			{
				if ((this._distype != value))
				{
					this.OndistypeChanging(value);
					this.SendPropertyChanging();
					this._distype = value;
					this.SendPropertyChanged("distype");
					this.OndistypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senurl", DbType="NVarChar(3500)")]
		public string senurl
		{
			get
			{
				return this._senurl;
			}
			set
			{
				if ((this._senurl != value))
				{
					this.OnsenurlChanging(value);
					this.SendPropertyChanging();
					this._senurl = value;
					this.SendPropertyChanged("senurl");
					this.OnsenurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Int")]
		public System.Nullable<int> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coupon", DbType="NVarChar(2500)")]
		public string coupon
		{
			get
			{
				return this._coupon;
			}
			set
			{
				if ((this._coupon != value))
				{
					this.OncouponChanging(value);
					this.SendPropertyChanging();
					this._coupon = value;
					this.SendPropertyChanged("coupon");
					this.OncouponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="NVarChar(2500)")]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this.OncommentsChanging(value);
					this.SendPropertyChanging();
					this._comments = value;
					this.SendPropertyChanged("comments");
					this.OncommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifydate", DbType="Date")]
		public System.Nullable<System.DateTime> modifydate
		{
			get
			{
				return this._modifydate;
			}
			set
			{
				if ((this._modifydate != value))
				{
					this.OnmodifydateChanging(value);
					this.SendPropertyChanging();
					this._modifydate = value;
					this.SendPropertyChanged("modifydate");
					this.OnmodifydateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat1", DbType="NVarChar(2500)")]
		public string cat1
		{
			get
			{
				return this._cat1;
			}
			set
			{
				if ((this._cat1 != value))
				{
					this.Oncat1Changing(value);
					this.SendPropertyChanging();
					this._cat1 = value;
					this.SendPropertyChanged("cat1");
					this.Oncat1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat2", DbType="NVarChar(2500)")]
		public string cat2
		{
			get
			{
				return this._cat2;
			}
			set
			{
				if ((this._cat2 != value))
				{
					this.Oncat2Changing(value);
					this.SendPropertyChanging();
					this._cat2 = value;
					this.SendPropertyChanged("cat2");
					this.Oncat2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
