<?xml version="1.0" encoding="utf-8"?><Database Name="adsrush" Class="CategoriesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=adsrush.database.windows.net;Initial Catalog=adsrush;User ID=tamordy" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="adsrushConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Table_AdsRushX_Categories" Member="Table_AdsRushX_Categories">
    <Type Name="Table_AdsRushX_Category">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="category" Type="System.String" DbType="NVarChar(3500)" CanBeNull="true" />
      <Column Name="icon" Type="System.String" DbType="NVarChar(3500)" CanBeNull="true" />
      <Column Name="graylogo" Type="System.String" DbType="NVarChar(3500)" CanBeNull="true" />
      <Column Name="whitelogo" Type="System.String" DbType="NVarChar(3500)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(3500)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(3000)" CanBeNull="true" />
      <Column Name="related_group" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rank" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>