#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsRushX
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="adsrush")]
	public partial class PublishersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_AdsRushX_Publisher(Table_AdsRushX_Publisher instance);
    partial void UpdateTable_AdsRushX_Publisher(Table_AdsRushX_Publisher instance);
    partial void DeleteTable_AdsRushX_Publisher(Table_AdsRushX_Publisher instance);
    partial void InsertTable_AdsRushX_Publishers_Campaign(Table_AdsRushX_Publishers_Campaign instance);
    partial void UpdateTable_AdsRushX_Publishers_Campaign(Table_AdsRushX_Publishers_Campaign instance);
    partial void DeleteTable_AdsRushX_Publishers_Campaign(Table_AdsRushX_Publishers_Campaign instance);
    partial void InsertTable_AdsRushX_Publishers_Stat(Table_AdsRushX_Publishers_Stat instance);
    partial void UpdateTable_AdsRushX_Publishers_Stat(Table_AdsRushX_Publishers_Stat instance);
    partial void DeleteTable_AdsRushX_Publishers_Stat(Table_AdsRushX_Publishers_Stat instance);
    #endregion
		
		public PublishersDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["adsrushConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PublishersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PublishersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PublishersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PublishersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_AdsRushX_Publisher> Table_AdsRushX_Publishers
		{
			get
			{
				return this.GetTable<Table_AdsRushX_Publisher>();
			}
		}
		
		public System.Data.Linq.Table<Table_AdsRushX_Publishers_Campaign> Table_AdsRushX_Publishers_Campaigns
		{
			get
			{
				return this.GetTable<Table_AdsRushX_Publishers_Campaign>();
			}
		}
		
		public System.Data.Linq.Table<Table_AdsRushX_Publishers_Stat> Table_AdsRushX_Publishers_Stats
		{
			get
			{
				return this.GetTable<Table_AdsRushX_Publishers_Stat>();
			}
		}
		
		public System.Data.Linq.Table<Table_AdsRushX_Publishers_Banner> Table_AdsRushX_Publishers_Banners
		{
			get
			{
				return this.GetTable<Table_AdsRushX_Publishers_Banner>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_AdsRushX_Publishers")]
	public partial class Table_AdsRushX_Publisher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _aid;
		
		private System.Nullable<int> _referaid;
		
		private string _referusername;
		
		private string _email;
		
		private string _username;
		
		private string _password;
		
		private string _fullname;
		
		private string _country;
		
		private string _paymentmethod;
		
		private string _skype;
		
		private string _whatsapp;
		
		private System.Nullable<int> _active;
		
		private System.Nullable<int> _suspended;
		
		private System.Nullable<System.DateTime> _signupdate;
		
		private string _signupip;
		
		private System.Nullable<float> _balance;
		
		private System.Nullable<float> _lastpayout;
		
		private System.Nullable<System.DateTime> _lastpayoutdate;
		
		private string _facebook;
		
		private string _linkedin;
		
		private string _websiteurl;
		
		private string _kind;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnaidChanging(System.Nullable<int> value);
    partial void OnaidChanged();
    partial void OnreferaidChanging(System.Nullable<int> value);
    partial void OnreferaidChanged();
    partial void OnreferusernameChanging(string value);
    partial void OnreferusernameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnpaymentmethodChanging(string value);
    partial void OnpaymentmethodChanged();
    partial void OnskypeChanging(string value);
    partial void OnskypeChanged();
    partial void OnwhatsappChanging(string value);
    partial void OnwhatsappChanged();
    partial void OnactiveChanging(System.Nullable<int> value);
    partial void OnactiveChanged();
    partial void OnsuspendedChanging(System.Nullable<int> value);
    partial void OnsuspendedChanged();
    partial void OnsignupdateChanging(System.Nullable<System.DateTime> value);
    partial void OnsignupdateChanged();
    partial void OnsignupipChanging(string value);
    partial void OnsignupipChanged();
    partial void OnbalanceChanging(System.Nullable<float> value);
    partial void OnbalanceChanged();
    partial void OnlastpayoutChanging(System.Nullable<float> value);
    partial void OnlastpayoutChanged();
    partial void OnlastpayoutdateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastpayoutdateChanged();
    partial void OnfacebookChanging(string value);
    partial void OnfacebookChanged();
    partial void OnlinkedinChanging(string value);
    partial void OnlinkedinChanged();
    partial void OnwebsiteurlChanging(string value);
    partial void OnwebsiteurlChanged();
    partial void OnkindChanging(string value);
    partial void OnkindChanged();
    #endregion
		
		public Table_AdsRushX_Publisher()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aid", DbType="Int")]
		public System.Nullable<int> aid
		{
			get
			{
				return this._aid;
			}
			set
			{
				if ((this._aid != value))
				{
					this.OnaidChanging(value);
					this.SendPropertyChanging();
					this._aid = value;
					this.SendPropertyChanged("aid");
					this.OnaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referaid", DbType="Int")]
		public System.Nullable<int> referaid
		{
			get
			{
				return this._referaid;
			}
			set
			{
				if ((this._referaid != value))
				{
					this.OnreferaidChanging(value);
					this.SendPropertyChanging();
					this._referaid = value;
					this.SendPropertyChanged("referaid");
					this.OnreferaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referusername", DbType="NVarChar(3500)")]
		public string referusername
		{
			get
			{
				return this._referusername;
			}
			set
			{
				if ((this._referusername != value))
				{
					this.OnreferusernameChanging(value);
					this.SendPropertyChanging();
					this._referusername = value;
					this.SendPropertyChanged("referusername");
					this.OnreferusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(3500)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(3500)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(3500)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(3500)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(3500)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymentmethod", DbType="NVarChar(3500)")]
		public string paymentmethod
		{
			get
			{
				return this._paymentmethod;
			}
			set
			{
				if ((this._paymentmethod != value))
				{
					this.OnpaymentmethodChanging(value);
					this.SendPropertyChanging();
					this._paymentmethod = value;
					this.SendPropertyChanged("paymentmethod");
					this.OnpaymentmethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skype", DbType="NVarChar(3500)")]
		public string skype
		{
			get
			{
				return this._skype;
			}
			set
			{
				if ((this._skype != value))
				{
					this.OnskypeChanging(value);
					this.SendPropertyChanging();
					this._skype = value;
					this.SendPropertyChanged("skype");
					this.OnskypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whatsapp", DbType="NVarChar(3500)")]
		public string whatsapp
		{
			get
			{
				return this._whatsapp;
			}
			set
			{
				if ((this._whatsapp != value))
				{
					this.OnwhatsappChanging(value);
					this.SendPropertyChanging();
					this._whatsapp = value;
					this.SendPropertyChanged("whatsapp");
					this.OnwhatsappChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Int")]
		public System.Nullable<int> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suspended", DbType="Int")]
		public System.Nullable<int> suspended
		{
			get
			{
				return this._suspended;
			}
			set
			{
				if ((this._suspended != value))
				{
					this.OnsuspendedChanging(value);
					this.SendPropertyChanging();
					this._suspended = value;
					this.SendPropertyChanged("suspended");
					this.OnsuspendedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signupdate", DbType="Date")]
		public System.Nullable<System.DateTime> signupdate
		{
			get
			{
				return this._signupdate;
			}
			set
			{
				if ((this._signupdate != value))
				{
					this.OnsignupdateChanging(value);
					this.SendPropertyChanging();
					this._signupdate = value;
					this.SendPropertyChanged("signupdate");
					this.OnsignupdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signupip", DbType="NVarChar(3500)")]
		public string signupip
		{
			get
			{
				return this._signupip;
			}
			set
			{
				if ((this._signupip != value))
				{
					this.OnsignupipChanging(value);
					this.SendPropertyChanging();
					this._signupip = value;
					this.SendPropertyChanged("signupip");
					this.OnsignupipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance", DbType="Real")]
		public System.Nullable<float> balance
		{
			get
			{
				return this._balance;
			}
			set
			{
				if ((this._balance != value))
				{
					this.OnbalanceChanging(value);
					this.SendPropertyChanging();
					this._balance = value;
					this.SendPropertyChanged("balance");
					this.OnbalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastpayout", DbType="Real")]
		public System.Nullable<float> lastpayout
		{
			get
			{
				return this._lastpayout;
			}
			set
			{
				if ((this._lastpayout != value))
				{
					this.OnlastpayoutChanging(value);
					this.SendPropertyChanging();
					this._lastpayout = value;
					this.SendPropertyChanged("lastpayout");
					this.OnlastpayoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastpayoutdate", DbType="Date")]
		public System.Nullable<System.DateTime> lastpayoutdate
		{
			get
			{
				return this._lastpayoutdate;
			}
			set
			{
				if ((this._lastpayoutdate != value))
				{
					this.OnlastpayoutdateChanging(value);
					this.SendPropertyChanging();
					this._lastpayoutdate = value;
					this.SendPropertyChanged("lastpayoutdate");
					this.OnlastpayoutdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facebook", DbType="NVarChar(3500)")]
		public string facebook
		{
			get
			{
				return this._facebook;
			}
			set
			{
				if ((this._facebook != value))
				{
					this.OnfacebookChanging(value);
					this.SendPropertyChanging();
					this._facebook = value;
					this.SendPropertyChanged("facebook");
					this.OnfacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linkedin", DbType="NVarChar(3500)")]
		public string linkedin
		{
			get
			{
				return this._linkedin;
			}
			set
			{
				if ((this._linkedin != value))
				{
					this.OnlinkedinChanging(value);
					this.SendPropertyChanging();
					this._linkedin = value;
					this.SendPropertyChanged("linkedin");
					this.OnlinkedinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_websiteurl", DbType="NVarChar(2500)")]
		public string websiteurl
		{
			get
			{
				return this._websiteurl;
			}
			set
			{
				if ((this._websiteurl != value))
				{
					this.OnwebsiteurlChanging(value);
					this.SendPropertyChanging();
					this._websiteurl = value;
					this.SendPropertyChanged("websiteurl");
					this.OnwebsiteurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kind", DbType="NVarChar(2500)")]
		public string kind
		{
			get
			{
				return this._kind;
			}
			set
			{
				if ((this._kind != value))
				{
					this.OnkindChanging(value);
					this.SendPropertyChanging();
					this._kind = value;
					this.SendPropertyChanged("kind");
					this.OnkindChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_AdsRushX_Publishers_Campaign")]
	public partial class Table_AdsRushX_Publishers_Campaign : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _fullname;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _startdate;
		
		private string _campaignname;
		
		private string _campaignkeywords;
		
		private string _senurl;
		
		private System.Nullable<int> _active;
		
		private string _comments;
		
		private System.Nullable<System.DateTime> _modifydate;
		
		private string _cat1;
		
		private string _cat2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnstartdateChanging(System.Nullable<System.DateTime> value);
    partial void OnstartdateChanged();
    partial void OncampaignnameChanging(string value);
    partial void OncampaignnameChanged();
    partial void OncampaignkeywordsChanging(string value);
    partial void OncampaignkeywordsChanged();
    partial void OnsenurlChanging(string value);
    partial void OnsenurlChanged();
    partial void OnactiveChanging(System.Nullable<int> value);
    partial void OnactiveChanged();
    partial void OncommentsChanging(string value);
    partial void OncommentsChanged();
    partial void OnmodifydateChanging(System.Nullable<System.DateTime> value);
    partial void OnmodifydateChanged();
    partial void Oncat1Changing(string value);
    partial void Oncat1Changed();
    partial void Oncat2Changing(string value);
    partial void Oncat2Changed();
    #endregion
		
		public Table_AdsRushX_Publishers_Campaign()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(2500)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(2500)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(2500)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startdate", DbType="Date")]
		public System.Nullable<System.DateTime> startdate
		{
			get
			{
				return this._startdate;
			}
			set
			{
				if ((this._startdate != value))
				{
					this.OnstartdateChanging(value);
					this.SendPropertyChanging();
					this._startdate = value;
					this.SendPropertyChanged("startdate");
					this.OnstartdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaignname", DbType="NVarChar(2500)")]
		public string campaignname
		{
			get
			{
				return this._campaignname;
			}
			set
			{
				if ((this._campaignname != value))
				{
					this.OncampaignnameChanging(value);
					this.SendPropertyChanging();
					this._campaignname = value;
					this.SendPropertyChanged("campaignname");
					this.OncampaignnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaignkeywords", DbType="NVarChar(2500)")]
		public string campaignkeywords
		{
			get
			{
				return this._campaignkeywords;
			}
			set
			{
				if ((this._campaignkeywords != value))
				{
					this.OncampaignkeywordsChanging(value);
					this.SendPropertyChanging();
					this._campaignkeywords = value;
					this.SendPropertyChanged("campaignkeywords");
					this.OncampaignkeywordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senurl", DbType="NVarChar(3500)")]
		public string senurl
		{
			get
			{
				return this._senurl;
			}
			set
			{
				if ((this._senurl != value))
				{
					this.OnsenurlChanging(value);
					this.SendPropertyChanging();
					this._senurl = value;
					this.SendPropertyChanged("senurl");
					this.OnsenurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Int")]
		public System.Nullable<int> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="NVarChar(2500)")]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this.OncommentsChanging(value);
					this.SendPropertyChanging();
					this._comments = value;
					this.SendPropertyChanged("comments");
					this.OncommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifydate", DbType="Date")]
		public System.Nullable<System.DateTime> modifydate
		{
			get
			{
				return this._modifydate;
			}
			set
			{
				if ((this._modifydate != value))
				{
					this.OnmodifydateChanging(value);
					this.SendPropertyChanging();
					this._modifydate = value;
					this.SendPropertyChanged("modifydate");
					this.OnmodifydateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat1", DbType="NVarChar(2500)")]
		public string cat1
		{
			get
			{
				return this._cat1;
			}
			set
			{
				if ((this._cat1 != value))
				{
					this.Oncat1Changing(value);
					this.SendPropertyChanging();
					this._cat1 = value;
					this.SendPropertyChanged("cat1");
					this.Oncat1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat2", DbType="NVarChar(2500)")]
		public string cat2
		{
			get
			{
				return this._cat2;
			}
			set
			{
				if ((this._cat2 != value))
				{
					this.Oncat2Changing(value);
					this.SendPropertyChanging();
					this._cat2 = value;
					this.SendPropertyChanged("cat2");
					this.Oncat2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_AdsRushX_Publishers_Stats")]
	public partial class Table_AdsRushX_Publishers_Stat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _username;
		
		private System.Nullable<int> _month;
		
		private System.Nullable<int> _year;
		
		private System.Nullable<int> _imp;
		
		private System.Nullable<int> _clicks;
		
		private System.Nullable<float> _winbid;
		
		private System.Nullable<float> _earnings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnmonthChanging(System.Nullable<int> value);
    partial void OnmonthChanged();
    partial void OnyearChanging(System.Nullable<int> value);
    partial void OnyearChanged();
    partial void OnimpChanging(System.Nullable<int> value);
    partial void OnimpChanged();
    partial void OnclicksChanging(System.Nullable<int> value);
    partial void OnclicksChanged();
    partial void OnwinbidChanging(System.Nullable<float> value);
    partial void OnwinbidChanged();
    partial void OnearningsChanging(System.Nullable<float> value);
    partial void OnearningsChanged();
    #endregion
		
		public Table_AdsRushX_Publishers_Stat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_month", DbType="Int")]
		public System.Nullable<int> month
		{
			get
			{
				return this._month;
			}
			set
			{
				if ((this._month != value))
				{
					this.OnmonthChanging(value);
					this.SendPropertyChanging();
					this._month = value;
					this.SendPropertyChanged("month");
					this.OnmonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="Int")]
		public System.Nullable<int> year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this.OnyearChanging(value);
					this.SendPropertyChanging();
					this._year = value;
					this.SendPropertyChanged("year");
					this.OnyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imp", DbType="Int")]
		public System.Nullable<int> imp
		{
			get
			{
				return this._imp;
			}
			set
			{
				if ((this._imp != value))
				{
					this.OnimpChanging(value);
					this.SendPropertyChanging();
					this._imp = value;
					this.SendPropertyChanged("imp");
					this.OnimpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clicks", DbType="Int")]
		public System.Nullable<int> clicks
		{
			get
			{
				return this._clicks;
			}
			set
			{
				if ((this._clicks != value))
				{
					this.OnclicksChanging(value);
					this.SendPropertyChanging();
					this._clicks = value;
					this.SendPropertyChanged("clicks");
					this.OnclicksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_winbid", DbType="Real")]
		public System.Nullable<float> winbid
		{
			get
			{
				return this._winbid;
			}
			set
			{
				if ((this._winbid != value))
				{
					this.OnwinbidChanging(value);
					this.SendPropertyChanging();
					this._winbid = value;
					this.SendPropertyChanged("winbid");
					this.OnwinbidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_earnings", DbType="Real")]
		public System.Nullable<float> earnings
		{
			get
			{
				return this._earnings;
			}
			set
			{
				if ((this._earnings != value))
				{
					this.OnearningsChanging(value);
					this.SendPropertyChanging();
					this._earnings = value;
					this.SendPropertyChanged("earnings");
					this.OnearningsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_AdsRushX_Publishers_Banners")]
	public partial class Table_AdsRushX_Publishers_Banner
	{
		
		private int _id;
		
		private string _username;
		
		private string _fullname;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _startdate;
		
		private System.Nullable<System.DateTime> _modifydate;
		
		private System.Nullable<int> _active;
		
		private string _comments;
		
		private string _leaderboard;
		
		private string _superleaderboard;
		
		private string _billboard;
		
		private string _vertical;
		
		private string _rectangle;
		
		private string _custom;
		
		private System.Nullable<int> _superleaderboardrequest;
		
		private System.Nullable<int> _billboardrequest;
		
		private System.Nullable<int> _verticalrequest;
		
		private System.Nullable<int> _rectanglerequest;
		
		private System.Nullable<int> _customrequest;
		
		private System.Nullable<int> _customwidth;
		
		private System.Nullable<int> _customeheight;
		
		public Table_AdsRushX_Publishers_Banner()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(2500)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(2500)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this._fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(2500)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startdate", DbType="Date")]
		public System.Nullable<System.DateTime> startdate
		{
			get
			{
				return this._startdate;
			}
			set
			{
				if ((this._startdate != value))
				{
					this._startdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifydate", DbType="Date")]
		public System.Nullable<System.DateTime> modifydate
		{
			get
			{
				return this._modifydate;
			}
			set
			{
				if ((this._modifydate != value))
				{
					this._modifydate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Int")]
		public System.Nullable<int> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this._active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="NVarChar(3500)")]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this._comments = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leaderboard", DbType="NVarChar(MAX)")]
		public string leaderboard
		{
			get
			{
				return this._leaderboard;
			}
			set
			{
				if ((this._leaderboard != value))
				{
					this._leaderboard = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_superleaderboard", DbType="NVarChar(MAX)")]
		public string superleaderboard
		{
			get
			{
				return this._superleaderboard;
			}
			set
			{
				if ((this._superleaderboard != value))
				{
					this._superleaderboard = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billboard", DbType="NVarChar(MAX)")]
		public string billboard
		{
			get
			{
				return this._billboard;
			}
			set
			{
				if ((this._billboard != value))
				{
					this._billboard = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vertical", DbType="NVarChar(MAX)")]
		public string vertical
		{
			get
			{
				return this._vertical;
			}
			set
			{
				if ((this._vertical != value))
				{
					this._vertical = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rectangle", DbType="NVarChar(MAX)")]
		public string rectangle
		{
			get
			{
				return this._rectangle;
			}
			set
			{
				if ((this._rectangle != value))
				{
					this._rectangle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custom", DbType="NVarChar(MAX)")]
		public string custom
		{
			get
			{
				return this._custom;
			}
			set
			{
				if ((this._custom != value))
				{
					this._custom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_superleaderboardrequest", DbType="Int")]
		public System.Nullable<int> superleaderboardrequest
		{
			get
			{
				return this._superleaderboardrequest;
			}
			set
			{
				if ((this._superleaderboardrequest != value))
				{
					this._superleaderboardrequest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billboardrequest", DbType="Int")]
		public System.Nullable<int> billboardrequest
		{
			get
			{
				return this._billboardrequest;
			}
			set
			{
				if ((this._billboardrequest != value))
				{
					this._billboardrequest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verticalrequest", DbType="Int")]
		public System.Nullable<int> verticalrequest
		{
			get
			{
				return this._verticalrequest;
			}
			set
			{
				if ((this._verticalrequest != value))
				{
					this._verticalrequest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rectanglerequest", DbType="Int")]
		public System.Nullable<int> rectanglerequest
		{
			get
			{
				return this._rectanglerequest;
			}
			set
			{
				if ((this._rectanglerequest != value))
				{
					this._rectanglerequest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customrequest", DbType="Int")]
		public System.Nullable<int> customrequest
		{
			get
			{
				return this._customrequest;
			}
			set
			{
				if ((this._customrequest != value))
				{
					this._customrequest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customwidth", DbType="Int")]
		public System.Nullable<int> customwidth
		{
			get
			{
				return this._customwidth;
			}
			set
			{
				if ((this._customwidth != value))
				{
					this._customwidth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customeheight", DbType="Int")]
		public System.Nullable<int> customeheight
		{
			get
			{
				return this._customeheight;
			}
			set
			{
				if ((this._customeheight != value))
				{
					this._customeheight = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
